config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    authenticated :user do
      root 'categories#index', as: :authenticated_root
    end
  end

  root to: 'shared#splash'

  resources :categories, only: [:index, :new, :create, :show] do
    resources :budgets, only: [:index, :new, :create, :show]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :user
  has_many :category_budgets, foreign_key: :budget_id, dependent: :destroy

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :category_budgets, foreign_key: :category_id, class_name: 'CategoryBudget'
  has_many :budgets, through: :category_budgets

  validates :name, presence: true, uniqueness: { scope: :user_id }
  validates :icon, presence: true

  def total_amount
    budgets.sum(:amount)
  end
end

app/models/category_budget.rb
class CategoryBudget < ApplicationRecord
  belongs_to :category
  belongs_to :budget
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, foreign_key: :user_id, dependent: :destroy
  has_many :budgets, foreign_key: :user_id, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_budget, only: %i[show edit update destroy]

  # GET /budgets or /budgets.json
  def index
    @category = Category.find(params[:category_id])
    @current_user = current_user
    @budgets = Category.find(params[:category_id]).category_budgets.order(created_at: :desc)
  end

  # GET /budgets/1 or /budgets/1.json
  def show; end

  # GET /budgets/new
  def new
    @budget = Budget.new
  end

  # POST /budgets or /budgets.json
  def create
    @budget = current_user.budgets.new(budget_params)
    if @budget.save
      @category_budget = CategoryBudget.new(category_id: params[:category_id], budget_id: @budget.id)
      @category_budget.save
      redirect_to category_budgets_url(params[:category_id]), notice: 'Budget was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def budget_params
    params.require(:budget).permit(:name, :amount)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.where(user_id: current_user.id)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # POST /categories or /categories.json
  def create
    @category = current_user.categories.new(category_params)

    if @category.save
      redirect_to categories_url, notice: 'Category was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/shared_controller.rb
class SharedController < ApplicationController
  def splash; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/budgets/_budget.html.erb
<% if @budgets.length > 0 %>
  <% @budgets.each do |budget| %>
    <div class="p-2 mx-4">
      <div class="flex bg-white p-2 shadow-md">
        <div class="flex-none bg-cover text-center overflow-hidden">
          <img src="https://source.unsplash.com/user/c_v_r/100x100" width="80px">
        </div>
        <div class="px-4 w-full flex flex-col justify-around">
          <div class="flex justify-between">
            <div class="text-gray-500 text-sm"><%= budget.budget.name %></div>
            <div class="text-gray-900 font-bold text-sm">$<%= budget.budget.amount %></div>
          </div>
          <hr class="text-gray-50">
          <div class="flex items-center">
            <div class="text-xs">
              <p class="text-gray-400">
                <%= "#{budget.created_at.day} #{budget.created_at.strftime("%b")} #{budget.created_at.year}" %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="w-full flex justify-center">
    <%= link_to 'Back to Categories', categories_path, class: "shadow-inner mt-8 py-3 px-5 bg-gray-100 font-light text-xs" %>
  </div>
<% else %>
  <div class="pt-16 flex justify-center items-center text-red-500">
    <div class="text-center">
      <h1 class="text-xl font-medium">No transactions yet</h1>
    </div>
  </div>
<% end %>

app/views/budgets/_form.html.erb
<%= form_with(model: budget,  url: category_budgets_path(params[:category_id]), method: :post, class: "contents w-full max-w-sm") do |form| %>
  <% if budget.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium text-sm mt-3 text-center">
      <h2><%= pluralize(budget.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% budget.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="items-center p-8 mt-8">
    <%= form.text_field :name, class: "border-b border-gray-200 text-sm p-4 mb-4 w-full text-gray-700 leading-tight focus:border-b-primary-blue focus:outline-none", placeholder: 'Name' %>
    <%= form.number_field :amount, class: "border-b border-gray-200 text-sm p-4 mb-4 w-full text-gray-700 leading-tight focus:border-b-primary-blue focus:outline-none", placeholder: 'Amount' %>
  </div>
  <div class="inline">
    <%= form.submit 'Add Budget', class: "fixed bottom-0 w-full p-5 tracking-wider bg-secondary-green text-center uppercase text-white block font-medium text-sm" %>
  </div>

<% end %>

app/views/budgets/index.html.erb
<div class="w-full bg-gray-50 h-screen">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <div id="budgets" class="min-w-full">
    <%= render "budget" %>
  </div>
  <%= link_to 'Add New Transaction', new_category_budget_path, class: "fixed bottom-0 w-full p-5 tracking-wider bg-secondary-green text-center uppercase text-white block font-medium text-sm" %>
</div>

app/views/budgets/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <%= render "form", budget: @budget %>
  <div class="w-full flex justify-center">
    <%= link_to 'Back to Transaction', category_budgets_path(params[:category_id]), class: "shadow-inner mt-8 py-3 px-5 bg-gray-100 font-light text-xs" %>
  </div>
</div>

app/views/categories/_category.html.erb
<% if @categories.length > 0%>
  <% @categories.each do |category| %>
    <%= link_to category_budgets_path(category) do%>
    <div class="p-2 mx-4">
      <div class="flex bg-white p-2 shadow-md">
        <div class="flex-none bg-cover text-center overflow-hidden">
          <img src="<%= category.icon %>" class="w-[80px] h-[80px]">
        </div>
        <div class="px-4 w-full flex flex-col justify-around">
          <div class="flex justify-between">
            <div class="text-gray-500 text-sm"><%= category.name %></div>
            <div class="text-gray-900 font-bold text-sm">$<%= category.total_amount %></div>
          </div>
          <hr class="text-gray-50">
          <div class="flex items-center">
            <div class="text-xs">
              <p class="text-gray-400">
                <%= "#{category.created_at.day} #{category.created_at.strftime("%b")} #{category.created_at.year}" %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
<% else %>
  <div class="flex justify-center items-center text-red-500">
    <div class="text-center">
      <h1 class="text-xl font-medium">No categories yet</h1>
    </div>
  </div>
<% end %>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: "contents") do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium text-sm mt-3 text-center">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="items-center p-8 mt-8">
    <%= form.text_field :name, class: "border-b border-gray-200 text-sm p-4 mb-8 w-full text-gray-700 leading-tight focus:border-b-primary-blue focus:outline-none", placeholder: 'Name' %>
    <%= form.text_field :icon, class: "border-b border-gray-200 text-sm p-4 mb-8 w-full text-gray-700 leading-tight focus:border-b-primary-blue focus:outline-none", placeholder: 'Icon Url' %>
  </div>

  <div class="inline">
    <%= form.submit 'Create Category', class: "fixed bottom-0 w-full p-5 tracking-wider bg-secondary-green text-center uppercase text-white block font-medium text-sm" %>
  </div>
<% end %>

app/views/categories/index.html.erb
<div class="w-full bg-gray-50 h-screen">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <div id="categories" class=" py-8">
    <%= render "category" %>
  </div>
  <%= link_to 'Add New Category', new_category_path, class: "fixed bottom-0 w-full p-5 tracking-wider bg-secondary-green text-center uppercase text-white block font-medium text-sm" %>
</div>

app/views/categories/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <%= render "form", category: @category %>
  <div class="w-full flex justify-center">
    <%= link_to 'Back to Categories', categories_path, class: "shadow-inner mt-8 py-3 px-5 bg-gray-100 font-light text-xs" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budgetism</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <% if user_signed_in? %>
        <%= render 'shared/header' %>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="flex justify-between flex-wrap items-center bg-primary-blue px-5 py-3" >
    <div class="block lg:hidden">
      <button class=" flex items-center px-3 py-2 text-white hover:border-transparent hover:text-primary-blue hover:bg-white" onclick="openNav()">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5"> <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" /></svg>
      </button>
    </div>
    <!-- mobile menu -->
		<div id="sidenav" class="h-full w-0 text-white fixed z-10 top-0 left-0 bg-[#111] shadow-2xl overflow-x-hidden">
      <a href="javascript:void(0)" class="absolute top-0 mt-4 right-[25px] text-xl font-bold" onclick="closeNav()">&times;</a>
      <ul class="uppercase text-center tracking-widest">
        <li class="mt-32 mb-8 font-medium texxt-sm" >Welcome, <%= current_user.name %></li>
        <li class='mb-8 text-xs '><%= link_to 'Category', root_path %></li>
        <li class='mb-8 text-xs '><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>

    <div class="flex items-center flex-shrink-0 text-white">
      <span class="text-md tracking-wide uppercase">
        <% if current_page?(authenticated_root_path) || current_page?(categories_path) %>
            Categories
          <% elsif current_page?(new_category_path) %>
            Add Category
          <% elsif params[:category_id] && current_page?(new_category_budget_path) %>
            Add Budget
          <% else %>
            Transactions
        <% end %>
      </span>
    </div>
    <div class="block lg:flex lg:items-center lg:w-auto">
      <div>
        <a href="/" class="inline-block text-xs px-4 py-2 leading-none text-white hover:border-transparent hover:text-primary-blue hover:bg-white lg:mt-0">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5"><path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" /></svg>
        </a>
      </div>
    </div>
</nav>

<script>
function openNav() {
  document.getElementById("sidenav").style.width = "250px";
}

function closeNav() {
  document.getElementById("sidenav").style.width = "0";
}
</script>

app/views/shared/splash.html.erb
<div class='bg-[url("https://images.unsplash.com/photo-1544655152-4dc3bc4df059?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjN8fGJ1ZGdldHxlbnwwfDF8MHx8&auto=format&fit=crop&w=800&q=60")] backdrop-contrast-125 bg-white/30 bg-bottom w-full h-screen bg-cover'>
  <div class="backdrop-contrast-125 bg-white/30">
    <h1 class="text-4xl font-bold text-sky-700 text-center h-screen pt-32">Budgetism</h1>
  </div>
  <div class="flex flex-col justify-evenly items-center fixed bottom-0 w-full p-4">
    <%= link_to "Log in", new_user_session_path , class: "w-full mb-4 p-5 tracking-wider border-2 border-primary-blue text-primary-blue uppercase text-center block font-medium text-sm hover:bg-primary-blue hover:text-white" %>
    <%= link_to "Sign up", new_user_registration_path , class: "w-full p-5 tracking-wider bg-primary-blue text-center uppercase text-white block font-medium text-sm hover:border-2 hover:border-primary-blue hover:bg-white hover:text-primary-blue" %>
  </div>
</div>